version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
            - ./wordpress:/var/www/html
        links:
            - wordpress
        restart: always 
    mysql:
        image: mariadb
        env_file: 
            - ./env/DB.env
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        restart: always 
    wordpress:
        image: wordpress:4.7.1-php7.0-fpm
        env_file: 
            - ./env/WP.env
        ports:
            - '9000:9000'
        volumes:
            - ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            links:
            - mysql
        restart: always
